FG-119: add v3 to the TagsInputComponent + stories
ironSource/fusion-ui pull request #171
Opened 2023-02-27 07:23 UTC by AndyKIron

2023-03-01 08:23 UTC, chenlevin89 requested changes

2023-03-01 08:31 UTC, AndyKIron commented on projects/fusion-ui/components/tags-input/v3/tags-input.component.ts
> +@Component({
Oh... Sure!

2023-03-01 08:40 UTC, AndyKIron commented on projects/fusion-ui/components/tags-input/v3/tags-input.component.ts
> +@Component({
> Change detection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

added to schematics component setting for add it by-default
```
"schematics": {
    "@schematics/angular:component": {
        "style": "scss",
        "standalone": true,
        "changeDetection": "OnPush"
    }
}

2023-03-05 09:52 UTC, chenlevin89 approved these changes

2023-03-05 09:59 UTC, merged