Feature/fu 378
ironSource/fusion-ui pull request #40
Opened 2022-04-03 09:22 UTC by amitmo50

2022-04-10 09:22 UTC, danielbrazg requested changes

2022-04-10 09:22 UTC, danielbrazg commented on projects/fusion-ui/components/button/button.component-v3.scss
> +:host.fu-style-v3 {
update file like we talked about

2022-04-11 10:09 UTC, amitmo50 commented on projects/fusion-ui/components/button/button.component.ts
> +                <fusion-icon
need to separate v3 from v1 & v2

2022-04-11 15:40 UTC, amitmo50 commented on projects/fusion-ui/components/button/button.component.ts
> +                    *ngIf="isLoading && (selectedVersion === 1 || selectedVersion === 2)"
I change this but still need to separate between V2 & V1 and V3

2022-04-11 15:45 UTC, amitmo50 commented on projects/fusion-ui/components/button/button.component-v3.scss
> +@keyframes rotation {
will be move when Andy merge his branch

2022-04-11 15:45 UTC, amitmo50 commented on projects/fusion-ui/components/button/button.component-v3.scss
> +@import '../../src/style/scss/vars/mixins';
will be move when Andy merge his branch

2022-04-24 11:52 UTC, chenlevin89 approved these changes

2022-04-24 13:27 UTC, merged