fix(fu-397): V3 Calendar, Daterange, Date picker components
ironSource/fusion-ui pull request #59
Opened 2022-05-12 07:32 UTC by AndyKIron

Added also attribute selector `[fusion-button]`

2022-05-18 14:52 UTC, amitmo50 requested changes

2022-05-19 06:04 UTC, AndyKIron commented on projects/fusion-native/src/app/app-config.ts
> +    {name: `${PREFIX}-calendar-v1`, componentInstance: CalendarComponentV1},
To use this components v1 and v2 in native frameworks

2022-05-19 06:13 UTC, AndyKIron commented on projects/fusion-ui/components/datepicker/v1/datepicker-header/datepicker-header.component.spec.ts
> +import {IconModule} from '../../../icon';
Not change it for unit tests :)

2022-05-19 06:14 UTC, AndyKIron commented on projects/fusion-ui/components/datepicker/v1/datepicker.component.spec.ts
> +import {LogService} from '../../../services/log';
same here :)

2022-05-19 09:48 UTC, amitmo50 approved these changes

2022-05-19 10:18 UTC, merged